config/routes.rb
Rails.application.routes.draw do

  get 'transactions/new'

 root 'landing#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  
  resources :listings, shallow: true do
    resources :reservations, only: [:new, :create], shallow: true do
      resources :transactions, only: [:new,:create]
    end
  end

  

  get 'reservations/:id' => "reservations#show", as: 'reservation'

  

end

app/models/listing.rb
class Listing < ActiveRecord::Base
	belongs_to :user
	has_many :reservations
	mount_uploader :image, ImageUploader
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = current_user.listings.new(listing_params)
    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:title, :description, :location, :price, :image)
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<div>
<%= form_for @listing, :html => {:multipart => true} do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :location %><br>
    <%= f.text_field :location, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :price %><br>
    RM <%= f.number_field :price, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image, "Show us your place!" %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>


  <div class="form-group">
    <%= f.submit "List Now", class: "form-control" %>
  </div>
<% end %>
</div>

app/views/listings/edit.html.erb
<div class = "container">
  <div id = "center">
<h2>Editing Listing</h2>

<%= render 'form' %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>
</div>
</div>

app/views/listings/index.html.erb
<div class="container">

  <div class="jumbotron"><h1>Find A Home</h1>
  <p class="lead">Home away from home</p>
  </div>

  <p id="notice"><%= notice %></p>

  <div class="row marketing">   

    <% @listings.each do |listing| %>
        <div class="col-lg-6">
          <div class="each-listing">
            <h4><%= listing.title %></h4>
            <p><%= listing.description %></p>
            <p>Location: <%= listing.location %></p>
            <p>RM <%= listing.price %></p>

            <% if listing.user_id == current_user.id %>
              <p class="btn btn-sm btn-default"><%= link_to 'Edit', edit_listing_path(listing) %></p>
              <p class="btn btn-sm btn-default"><%= link_to 'Delete', listing, method: :delete, data: { confirm: 'Are you sure?' } %></p>
            <%else%>
              <p class="btn btn-sm btn-default"><%= link_to 'Book', new_listing_reservation_path(listing) %></p>
            <% end %>
            </div>
        </div>
    <% end %>

  </div>
</div>

<br>

app/views/listings/new.html.erb
<div class = "container">
  <div id = "center">
<h2>List Your Room</h2>

<%= render 'form' %>

<%= link_to 'Back', listings_path %>
</div>
</div>

app/views/listings/show.html.erb
<div id = "center">
<p id="notice"><%= notice %></p>

<%= image_tag(@listing.image_url(:thumb).to_s) %>
</div>
<div class = "container">
  <div id = "center">
  	<div class="row marketing">  
  		<div class="each-listing">
				<h4><%= @listing.title %></h4>

				<p>
				  <strong>Description:</strong>
				  <%= @listing.description %>
				</p>

				<p>
				  <strong>Location:</strong>
				  <%= @listing.location %>
				</p>

				<p>
				  <strong>Price:</strong>
				  <%= @listing.price %>
				</p>

				<%= link_to 'Edit', edit_listing_path(@listing) %> |
				<%= link_to 'Back', listings_path %>
			</div>
		</div>
	</div>
</div>