config/routes.rb
Rails.application.routes.draw do

  get 'transactions/new'

 root 'landing#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  
  resources :listings, shallow: true do
    resources :reservations, only: [:new, :create], shallow: true do
      resources :transactions, only: [:new,:create]
    end
  end

  

  get 'reservations/:id' => "reservations#show", as: 'reservation'

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
	    <meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
	    <meta name="description" content="">
	    <meta name="author" content="">
	  
	  	<title>HomeAway</title>
	  	<%= include_gon %>
		  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		  <%= csrf_meta_tags %>

	    <!-- Bootstrap Core CSS -->
	    <!-- <link href="css/bootstrap.min.css" rel="stylesheet"> -->

	    <!-- Custom CSS -->
	    <!-- <link href="css/landing-page.css" rel="stylesheet"> -->

	    <!-- Custom Fonts -->
	    <!-- <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"> -->
	    <link href="http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

	      <!-- ... 
		  <script type="text/javascript" src="/bower_components/jquery/jquery.min.js"></script>
		  <script type="text/javascript" src="/bower_components/moment/min/moment.min.js"></script>
		  <script type="text/javascript" src="/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
		  <script type="text/javascript" src="/bower_components/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js"></script>
		  <link rel="stylesheet" href="/bower_components/bootstrap/dist/css/bootstrap.min.css" />
		  <link rel="stylesheet" href="/bower_components/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css" />
      
	    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
	    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]
	    <script src="../../assets/js/ie-emulation-modes-warning.js"></script> -->
	    <script src="https://js.braintreegateway.com/v2/braintree.js"></script>

	</head>

	<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand topnav" href="/">HomeAway</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	            <ul class="nav navbar-nav navbar-right">
				        <li role="presentation"><a href="/">Home</a></li>
				        <% if current_user %>
				        <li><%= link_to 'Book a place', listings_path %></li>
				        <li><%= link_to 'New Listing', new_listing_path %></li>
				        <li><%= link_to 'Logout', destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure you want to log out?'} %></li>
				        <% else %>
				        <li><%= link_to 'Book a place', listings_path %></li>

				        <li role="presentation" data-target="#signupForm"><a href="#signupForm" data-toggle="modal" >Sign Up</a></li>

				        <li role="presentation"><a href="/users/sign_in">Log In</a></li>
				        <%end%>
			      	</ul>
		      	</div>

		    </div>  
		</nav>
<br>
<br>
<br>
		<%= yield %>
</div>

<div class="modal fade" id="signupForm" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-header">
          <h2>Sign Up</h2>
      </div>

      <div class="modal-body">
           <%= render template: "devise/registrations/new" %>
      </div>
      
      <div class="modal-footer">
        <p>fd</p>
      </div>

    </div>
  </div>
</div>          

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <p class="copyright text-muted small">Copyright &copy; Home Away 2015. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>


	 	    <!-- jQuery 
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript 
    <script src="js/bootstrap.min.js"></script>-->


	</body>
</html>